name: Deploy Notification

on:
  workflow_call:
    secrets:
      PORTAINER_WEBHOOK_URL:
        required: true
      WECHAT_WEBHOOK_KEY:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Notify Portainer Webhook
        run: |
          curl -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}"

      - name: Notify WeCom
        if: success()
        run: |
          curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}' \
           -H 'Content-Type: application/json' \
           -d '
           {
                "msgtype": "markdown",
                "markdown": {
                    "content": "项目构建部署成功！\n>项目: ${{ github.repository }}\n>分支: ${{ github.ref }}\n>提交: ${{ github.sha }}"
                }
           }'
