name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml

  build:
    needs: test
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-push.yml
    with:
      registry_ghcr: ghcr.io
      registry_tencent: hkccr.ccs.tencentyun.com
      image_name_tencent: gdgeek/a1
    secrets:
      TENCENT_CLOUD_USERNAME: ${{ secrets.TENCENT_CLOUD_USERNAME }}
      TENCENT_CLOUD_PASSWORD: ${{ secrets.TENCENT_CLOUD_PASSWORD }}

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/deploy-notify.yml
    secrets:
      PORTAINER_WEBHOOK_URL: ${{ secrets.PORTAINER_WEBHOOK_URL }}
      WECHAT_WEBHOOK_KEY: ${{ secrets.WECHAT_WEBHOOK_KEY }}
