name: Run Tests

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          extensions: mbstring, intl, pdo, pdo_sqlite
          coverage: none

      - name: Install Dependencies
        run: |
          cd api
          composer update --prefer-dist --no-progress

      - name: Security Audit
        run: |
          cd api
          composer audit --abandoned=report

      - name: Prepare Config
        run: |
          cp files/api/config/test.php api/config/test.php
          echo "<?php return ['class' => 'yii\db\Connection', 'dsn' => 'sqlite::memory:', 'charset' => 'utf8'];" > api/config/test_db.php
          cp files/api/config/params.php api/config/params.php

      - name: Run Tests
        run: |
          cd api
          vendor/bin/codecept run unit
